export function extractJsonString(raw, key) {
  const k = `"${key}"`;
  const i = raw.indexOf(k);
  if (i === -1) return null;
  const colon = raw.indexOf(":", i + k.length);
  if (colon === -1) return null;
  const firstQuote = raw.indexOf('"', colon + 1);
  if (firstQuote === -1) return null;

  let out = "";
  let esc = false;
  for (let p = firstQuote + 1; p < raw.length; p += 1) {
    const ch = raw[p];
    if (esc) {
      if (ch === "n") out += "\n";
      else if (ch === "t") out += "\t";
      else out += ch;
      esc = false;
      continue;
    }
    if (ch === "\\") {
      esc = true;
      continue;
    }
    if (ch === '"') return out;
    out += ch;
  }
  return out;
}

export function extractJsonBool(raw, key) {
  const k = `"${key}"`;
  const i = raw.indexOf(k);
  if (i === -1) return null;
  const colon = raw.indexOf(":", i + k.length);
  if (colon === -1) return null;
  const tail = raw.slice(colon + 1).trimStart();
  if (tail.startsWith("true")) return true;
  if (tail.startsWith("false")) return false;
  return null;
}

/**
 * Repair JSON that has literal newlines inside string values.
 * llama3.1 often outputs unescaped newlines in JSON strings.
 */
function repairJsonNewlines(text) {
  let result = "";
  let inString = false;
  let escape = false;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];

    if (escape) {
      result += ch;
      escape = false;
      continue;
    }

    if (ch === "\\") {
      result += ch;
      escape = true;
      continue;
    }

    if (ch === '"') {
      inString = !inString;
      result += ch;
      continue;
    }

    if (inString && ch === "\n") {
      result += "\\n";
      continue;
    }

    if (inString && ch === "\r") {
      continue; // skip \r
    }

    if (inString && ch === "\t") {
      result += "\\t";
      continue;
    }

    result += ch;
  }

  return result;
}

/**
 * Repair invalid JSON syntax commonly generated by local LLMs,
 * such as using backticks (\`) or single quotes (') for string boundaries.
 */
function repairJsonSyntax(text) {
  let repaired = text;
  
  // Replace: "key": """value""" with "key": "value"
  repaired = repaired.replace(/:\s*"""([\s\S]*?)"""/g, (match, inner) => {
    const escaped = inner.replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '');
    return `: "${escaped}"`;
  });

  // Replace: "key": `value` with "key": "value"
  repaired = repaired.replace(/:\s*\`([\s\S]*?)\`/g, (match, inner) => {
    // Escape double quotes and newlines inside the backticks
    const escaped = inner.replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '');
    return `: "${escaped}"`;
  });

  // Replace: "key": 'value' with "key": "value"
  repaired = repaired.replace(/:\s*'([\s\S]*?)'(?=\s*[,}\]])/g, (match, inner) => {
    const escaped = inner.replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '');
    return `: "${escaped}"`;
  });

  return repaired;
}

/**
 * Attempt to close an incomplete JSON string by appending missing
 * braces/brackets. Useful when the LLM stream is cut off mid-JSON.
 */
function tryCloseJson(text) {
  let inStr = false;
  let esc = false;
  const stack = [];

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (esc) { esc = false; continue; }
    if (ch === "\\") { esc = true; continue; }
    if (ch === '"') { inStr = !inStr; continue; }
    if (inStr) continue;
    if (ch === "{") stack.push("}");
    else if (ch === "[") stack.push("]");
    else if (ch === "}" || ch === "]") stack.pop();
  }

  // If we're in a string, close the string first
  let suffix = "";
  if (inStr) suffix += '"';

  // Close any remaining open braces/brackets
  while (stack.length) {
    suffix += stack.pop();
  }

  return text + suffix;
}

/**
 * Strip common LLM wrapping patterns from output.
 * Handles: "Here is the JSON:", "```json ... ```", prose after JSON, etc.
 */
function cleanLlmOutput(raw) {
  if (!raw || typeof raw !== "string") return "";

  let text = raw.trim();

  // Remove "Here is the JSON:" style preamble
  text = text.replace(/^(?:here\s+is\s+(?:the\s+)?(?:json|response|output|result)\s*[:.]?\s*)/i, "");

  // Remove trailing prose after JSON (after the last })
  // But only if there's a clear JSON block
  const lastBrace = text.lastIndexOf("}");
  if (lastBrace !== -1 && lastBrace < text.length - 1) {
    const after = text.slice(lastBrace + 1).trim();
    // If what follows doesn't look like more JSON, strip it
    if (after && !after.startsWith(",") && !after.startsWith("]")) {
      text = text.slice(0, lastBrace + 1);
    }
  }

  return text.trim();
}

/**
 * Extract JSON from raw LLM output that may contain markdown fences,
 * prose before/after, unescaped newlines in strings, or other non-JSON text.
 * Returns the parsed object or null.
 */
function repairLlmEscapeArtifacts(text) {
  if (!text || typeof text !== "string") return text;
  return text.replace(/\\\\"/g, '\\"').replace(/\\\\n/g, "\\n").replace(/\\\\t/g, "\\t");
}

export function extractJsonFromText(raw) {
  if (!raw || typeof raw !== "string") return null;

  const cleaned = cleanLlmOutput(raw);
  const syntaxRepaired = repairLlmEscapeArtifacts(repairJsonSyntax(cleaned));

  // 1. Try direct parse first
  try {
    return JSON.parse(syntaxRepaired);
  } catch {
    // continue
  }

  // 2. Strip markdown code fences: ```json ... ``` or ``` ... ```
  const fenceMatch = syntaxRepaired.match(/```(?:json|JSON)?\s*\n?([\s\S]*?)```/);
  if (fenceMatch) {
    const inner = fenceMatch[1].trim();
    try {
      return JSON.parse(inner);
    } catch {
      // Try with newline repair
      try {
        return JSON.parse(repairJsonNewlines(inner));
      } catch {
        // Try closing incomplete JSON
        try {
          return JSON.parse(tryCloseJson(repairJsonNewlines(inner)));
        } catch {
          // continue
        }
      }
    }
  }

  // 3. Find the first { ... } block using brace counting
  const start = syntaxRepaired.indexOf("{");
  if (start !== -1) {
    let depth = 0;
    let inStr = false;
    let esc = false;
    for (let i = start; i < syntaxRepaired.length; i++) {
      const ch = syntaxRepaired[i];
      if (esc) { esc = false; continue; }
      if (ch === "\\") { esc = true; continue; }
      if (ch === '"') { inStr = !inStr; continue; }
      if (inStr) continue;
      if (ch === "{") depth++;
      if (ch === "}") {
        depth--;
        if (depth === 0) {
          const block = syntaxRepaired.slice(start, i + 1);
          // Try direct parse
          try {
            return JSON.parse(block);
          } catch {
            // Try with newline repair
            try {
              return JSON.parse(repairJsonNewlines(block));
            } catch {
              return null;
            }
          }
        }
      }
    }

    // If depth > 0, the JSON is incomplete — try closing it
    if (depth > 0) {
      const block = syntaxRepaired.slice(start);
      try {
        return JSON.parse(tryCloseJson(repairJsonNewlines(block)));
      } catch {
        // last resort
      }
    }
  }

  return null;
}

/**
 * Shared safe JSON parse — tries extractJsonFromText first.
 */
export function safeJsonParse(text) {
  return extractJsonFromText(text);
}
